info:
  component: Config Server
spring:
  application:
    name: configserver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/osswangxining/config-repo
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/osswangxining/config-repo

server:
  port: 8888
management:
  context_path: /admin
  security:
    enabled: false
